#!/bin/bash
cd /tmp/rom # Depends on where source got synced

# Deps
sudo apt-get install cpio -y
sudo apt-get install python2 -y

# Normal build steps
. build/envsetup.sh
lunch "${rom}"_miatoll-"${build_type}" 
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

if [ $with_gapps == "true" ];then
  export WITH_GAPPS=true && export TARGET_GAPPS_ARCH=arm64
else
  export WITH_GAPPS=false
fi

ccache -M 75G # It took only 6.4GB for mido
ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
ccache -z # Clear old stats, so monitor script will provide real ccache statistics

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache

# Build Machine details
cores=$(nproc --all)
os=$(cat /etc/issue)
time=$(TZ="Asia/Kolkata" date "+%a %b %d %r")

START=$(date +%s)
cilink="https://cirrus-ci.com/github/projectlegionos/aosp-buildernew"

# Let's compile by parts! Coz of ram issue!
make api-stubs-docs
make hiddenapi-lists-docs
make system-api-stubs-docs
make test-api-stubs-docs

# Build command! j10 for 10 cpu, j8 for 8 cpu, otherwise memeroy will end up even its 24G
$make -j8 |& tee log.txt

END=$(date +%s)
BUILDTIME=$(echo $((${END} - ${START})) | awk '{print int ($1/3600)" Hours: "int(($1/60)%60)" Minutes: "int($1%60)" Seconds"}')

  size="$(du -h ${zip}|awk '{print $1}')"
	mdsum="$(md5sum ${zip}|awk '{print $1}')"
  file=$(basename $zip)
  rclone -P copy $zip drive:Builds/$gdrivedir #fetches the drive link
  glink="$(rclone link drive:Builds/${gdrivedir}/${file})" 
  index="https://builds.projectlegionos.workers.dev/0:/${gdrivedir}/${file}" # sets up an index link also

ccache -s
