#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# This is a test and i don't know if it will work or not
git config --global user.name "Logan"
git config --global user.email "athuldineshan5@gmail.com"
git config --global core.editor vim
git config --global credential.helper store
echo "https://athul05:$password@github.com" > ~/.git-credentials

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
if [ $rom == "havoc" ];then
  repo init -q --no-repo-verify --depth=1 -u https://github.com/VIOLET-ANDROID/manifest.git -b private -g default,-device,-mips,-darwin,-notdefault
else
  repo init -q --no-repo-verify --depth=1 -u git://github.com/ColtOSTemp/platform_manifest.git -b c11 -g default,-device,-mips,-darwin,-notdefault
fi
  
# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

git clone https://github.com/athul05/android_device_xiaomi_violet.git -b $branch device/xiaomi/violet

git clone --depth=1 https://gitlab.com/athul05/vendor_xiaomi_violet.git vendor/xiaomi/violet

git clone --depth=1 https://github.com/SuperiorOS-Devices/android_kernel_xiaomi_violet.git kernel/xiaomi/violet

# Change Default hals
rm -rf  hardware/qcom-caf/sm8150/{display,media,audio}

cd hardware/qcom-caf/sm8150 && git clone https://github.com/PixelExperience/hardware_qcom-caf_sm8150_display.git display && git clone https://github.com/PixelExperience/hardware_qcom-caf_sm8150_media.git media && git clone https://github.com/PixelExperience/hardware_qcom-caf_sm8150_audio.git audio && cd -
