#!/bin/bash

cd /tmp

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

if [ $with_gapps == "true"  ];then # This is me testing out whether ccache's of vanilla and gapps build vary in build time...May remove this check in future
    time rclone copy ccache.tar.gz drive:ccache/legion-gapps -P
else
    time rclone copy ccache.tar.gz drive:ccache/legion-vanilla -P
fi
